### ISSUE TITLE
Mosaic of all the images

### ISSUE THREAD

**Issue by Komzpa** [hotosm/OpenAerialMap#103]
Hi,

We're making photos of town using Mavic. 
We've made a good amount of flights and we're not currently sure where we need more flights to fill the gaps :)

On SOTM US there was a demo of mosaic of all the available images. Can it be deployed and implemented please? :)

**Comment by mojodna** [comment]
In progress here: https://github.com/hotosm/oam-catalog/pull/122 and https://github.com/mojodna/marblecutter-openaerialmap

(I've been away from OAM for a while but am back.)

**Comment by dktue** [comment]
Doing the same here, would be awesome to have a map with coverage of many flights!

**Comment by dktue** [comment]
I'd love to have a mosaic where I can freely chose multiple images (from different users) and a way to sort their z-level to manage the overlapping areas.

**Comment by dktue** [comment]
Being able to save such a collection and expose it as new mosaic being available for everybody would be nice. This way mutliple users can can collaborate and create a single mosaic covering a whole city.

**Comment by bgirardot** [comment]
@mojodna Hi Seth, this looks merged and I have seen it mentioned, but could you point to instructions on how to use this feature now or just tell us in a few sentences here and I'll make sure it gets added to the docs.

**Comment by mojodna** [comment]
User-specific mosaics have been implemented; we're (slowly) working on a UI to create curated mosaics.

The TMS for a user mosaic is e.g. http://tiles.openaerialmap.org/user/5b2fdd372b6a08001185f877/{z}/{x}/{y}@2x

**Comment by Komzpa** [comment]
Hi,
can we have a global autogenerated mosaic that will just put most recent imagery on top? That will bring 90% of usablility ("to fix issues just upload better image") and will not require an UI.

**Comment by cgiovando** [comment]
Closing in favor of #108
