### ISSUE TITLE
(bug) 401 Unauthorized token when trying to get tms tiles

### ISSUE THREAD

**Issue by asafMasa** [hotosm/OpenAerialMap#104]
*reproduce*
1. ask for image via https://api.openaerialmap.org/meta?limit=501&bbox=3.666723,45.535928,3.666748,45.535946&acquisition_from=2012-03-01T11:11:00.000Z&acquisition_to=2018-03-22T11:11:23.538Z

2. get image url from properties.tms

3. try to load the tile via its url
http://a.tiles.mapbox.com/v4/astrodigital.LC81980282015359LGN00_bands_432/%7B1%7D/%7B1%7D/%7B1%7D.png?access_token=pk.eyJ1IjoiYXN0cm9kaWdpdGFsIiwiYSI6ImNVb1B0ZkEifQ.IrJoULY2VMSBNFqHLrFYew

Expected: 200 (valid Tile)
Actual: 
401 Unauthorized
{
"message": "Not Authorized - Invalid Token"
}

**Comment by mojodna** [comment]
Astro Digital has either removed this Landsat scene from Mapbox or changed their access token. There's nothing we can do on OAM's end other than remove the TMS link from the catalog.

**Comment by bgirardot** [comment]
@asafMasa Hi, wondering if Seths answer above "resolves" this issue for you? It seems like we can not correct it from our end. 

If this does not resolve the issue for you, please re-open this and let us know.

Thank you for using OAM and taking the time to report this here so we all can learn from it, I know I did.

**Comment by mikelmaron** [comment]
@bgirardot @smit1678 @mojodna can we remove broken astrodigital layers from the OAM index, so they are not cluttering up end user experience?
