### ISSUE TITLE
CORS HTTP Access-Control-Allow-Origin header is missing

### ISSUE THREAD

**Issue by jekhor** [hotosm/OpenAerialMap#106]
When uploading, I don't see changes in progress indicator and see following messages in browser debug console:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://oam-uploader-production-temp.s3.amazonaws.com/Project-2018-04-15_transparent_mosaic_group1-ilmlsfal.tif?uploads. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by bgirardot** [comment]
@smit1678 This could be related to some of the "blank pages" I see all the time in OAM urls when trying to share them or non loading pages like links from My Profile page.
