### ISSUE TITLE
Import Status page - link to imagery when finished doesn't work

### ISSUE THREAD

**Issue by bgirardot** [hotosm/OpenAerialMap#118]
When my upload is finished processing, there is a link to "View Image" but it does not work, nothing happens when I click it, i can not right click to "copy the url" even.

When I click on it I get the following in my console in Chrome:
![2018-08-19_11h10_50](https://user-images.githubusercontent.com/265831/44310216-8cf8a380-a3a0-11e8-9eef-5ed87c3c1b56.png)

**Comment by cgiovando** [comment]
Caused by same issue? https://github.com/hotosm/oam-browser/issues/290
