### ISSUE TITLE
WMTS does not work on some images

### ISSUE THREAD

**Issue by cgiovando** [hotosm/OpenAerialMap#125]
WMTS for this image in Tonga works: `http://tiles.openaerialmap.org/5aa6c1122553e6000ce5ad90/1/1584ee19-31bd-45e4-bcb3-cf690e98d0e2/wmts`

This one in Zanzibar doesn't: `http://tiles.openaerialmap.org/5ae38a550b093000130aff29/0/5ae38a550b093000130aff2a/wmts?`

Tested in QGIS and direct [GetCapabilities request](http://tiles.openaerialmap.org/5ae38a550b093000130aff29/0/5ae38a550b093000130aff2a/wmts?SERVICE=WMS&REQUEST=GetCapabilities) - getting `Internal Server Error`

**Comment by sfkeller** [comment]
I can confirm and replicate this http error 500 (software programming) error in QGIS 2.18 LTE, 3.4 (LTE) and in browser.
