### ISSUE TITLE
OpenAerialMap creates bad black edges on imagery

### ISSUE THREAD

**Issue by Komzpa** [hotosm/OpenAerialMap#127]
Original:
![image](https://user-images.githubusercontent.com/810638/45168232-6db49f80-b203-11e8-8c59-922b551e0417.png)

On OpenAerialMap:
![image](https://user-images.githubusercontent.com/810638/45168253-7c9b5200-b203-11e8-8421-3c9d71038a70.png)

This looks like OpenAerialMap does not maintain image transparency mask and recompresses into JPEG without it.

Current imagery can be fixed using Nearblack utility, for future ones please use nodata bit mask:
```
gdal_translate rgba.tif withmask.tif -b 1 -b 2 -b 3 -mask 4 -co COMPRESS=JPEG -co PHOTOMETRIC=YCBCR --config GDAL_TIFF_INTERNAL_MASK YES
```
(quote from https://www.gdal.org/gdal_translate.html)

**Comment by mojodna** [comment]
This is now fixed for imagery that's been uploaded within the past month or so (and all new imagery going forward).
