### ISSUE TITLE
Direct link copied from URL bar fails to load

### ISSUE THREAD

**Issue by Komzpa** [hotosm/OpenAerialMap#128]
Link:
https://map.openaerialmap.org/#/27.569959759712216,53.88930000254405,18/square/1203003112031032322/5b919d93c4be300007b23c69?_k=bgzhpb

Shows white screen. Console errors:

![image](https://user-images.githubusercontent.com/810638/45234951-002a7100-b2e0-11e8-9338-ad42daf4d88b.png)

**Comment by lukaszkruk** [comment]
I think this may be the same as #119

**Comment by cgiovando** [comment]
Duplicate of https://github.com/hotosm/oam-browser/issues/290
