### ISSUE TITLE
Problem loading maps in Chrome browser

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/OpenAerialMap#131]
While using - https://coordination.openaerialmap.org/#/imagery-search/69.12159898232903,34.55266679676957,14.894938453190282 
![image](https://user-images.githubusercontent.com/12103383/46123909-360da600-c24b-11e8-8fce-bae8ff475e9d.png)
maps don’t load in chrome browser and the console has a bunch of `404` errors. However the same link works good in firefox without a login
Is this a known chrome issue?

**Comment by smit1678** [comment]
Looks like this is something to do with Auth0. We need to look into our account and make sure it's still working correctly.
