### ISSUE TITLE
AstroDigital OIN bucket is missing

### ISSUE THREAD

**Issue by cgiovando** [hotosm/OpenAerialMap#132]
All of AstroDigital Landsat imagery is missing

https://map.openaerialmap.org/#/32.7690402777778,-0.0040715193312129165,8/square/12232333221301021/59e62c3b3d6412ef7220db75?_k=yjtaim

```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>oin-astrodigital</BucketName>
<RequestId>9D97D05FA16309FD</RequestId>
<HostId>
bJiM1/zxWZkdDQABPNwbb824H/OSGByrWVyRl19V5Oq/SfyzslhRGmMunPYMiG9yWAUx3w3fHwI=
</HostId>
</Error>
```

**Comment by Boukary** [comment]
I have same issue, all AstroDigital images are missing, is there anything to fix this?

**Comment by IpswichMapper** [comment]
Close this issue. AstroDigital has been removed
