### ISSUE TITLE
REMOVE astrodigital FROM OAM

### ISSUE THREAD

**Issue by IpswichMapper** [hotosm/OpenAerialMap#141]
[An issue was created about this **2 years ago**](https://github.com/hotosm/OpenAerialMap/issues/104), and the suggested solution was to remove astrodigital yet it hasn't been done. 

[Someone even tried to remove it](https://github.com/hotosm/oam-api/issues/147), turns out you have to remove it from the database, and then only it will go. Can this be done, **please**??

**Comment by dakotabenjamin** [comment]
The astro digital imagery has been removed.

**Comment by IpswichMapper** [comment]
Thanks.
