### ISSUE TITLE
how to link to a specific image?

### ISSUE THREAD

**Issue by danbjoseph** [hotosm/OpenAerialMap#142]
How to share a link to a specific image?

I navigate to an image, click it, and copy the URL.

<img width="1265" alt="Screen Shot 2020-12-03 at 9 09 27 PM" src="https://user-images.githubusercontent.com/4806884/101112766-0d606400-35ac-11eb-83a3-0b9865405f52.png">

Paste it into another browser window, comes up blank.

<img width="1261" alt="Screen Shot 2020-12-03 at 9 09 56 PM" src="https://user-images.githubusercontent.com/4806884/101112789-18b38f80-35ac-11eb-9097-b9062515f905.png">

**Comment by justinelliotmeyers** [comment]
@danbjoseph did you ever figure this out?

**Comment by danbjoseph** [comment]
no, i did not.

**Comment by cgiovando** [comment]
Hi @danbjoseph - this a known issue with some browsers (see https://github.com/hotosm/oam-browser/issues/290). We are working on some fixes and improvements that will solve this issue. I'll come back here with an update once it's fixed.

**Comment by cgiovando** [comment]
Closing here and tracking at https://github.com/hotosm/oam-browser/issues/290
