### ISSUE TITLE
Names of images does not support spaces

### ISSUE THREAD

**Issue by angoca** [hotosm/OpenAerialMap#144]
I was trying to update a name with several spaces, and it said there was a problem. After trying multiple things, I found the spaces were the problem

**Comment by cgiovando** [comment]
Hi @angoca - I tried updating names to images in my account, but I'm not getting the error you mention. Can you post a screenshot/screencast of when the problem happens? Thanks

**Comment by cgiovando** [comment]
Closing for now, but please reopen if the problem persists

**Comment by jekhor** [comment]
Reproduced. When I tried to upload file with space in its name, the message "Form contains errors" shown without of additional details. In te debugger console I found message about invalid image URL (see image). After renaming of the file, problem was gone.

The filename was 'arabika-21 camp-pereval.tif'

![image](https://user-images.githubusercontent.com/117467/133907593-3dc21a17-ee98-4112-a07a-bd8e2f604774.png)
