### ISSUE TITLE
URL cannot be shared

### ISSUE THREAD

**Issue by angoca** [hotosm/OpenAerialMap#147]
I am trying to share an image, even using the option "share in twitter", but the link does not work. This is an example:
https://map.openaerialmap.org/#/-74.05128479003906,4.712618660958392,16/square/032232112121031301/604c3ffe5553510005076089?_k=xppngm 
It loads a while, but the page is empty.

**Comment by cgiovando** [comment]
Thanks @angoca - this looks like the same issue as https://github.com/hotosm/oam-browser/issues/290 - tracking there.

A patch was created, it just needs to be deployed on the live browser instance.
