### ISSUE TITLE
Subdomain Takeover

### ISSUE THREAD

**Issue by JoeMilian** [hotosm/OpenAerialMap#148]
Hey,

I noticed you had an unclaimed GitHub page, I took it over so no attacker is able to use it.

The subdomain: https://browser.openaerialmap.org/

Github suggests the following: "We strongly recommend not using wildcard DNS records, such as *.example.com. A wildcard DNS record will allow anyone to host a site at one of your subdomains."

I hope I have informed you enough, If there are any issues please don't hesitate to message me.

Kind regards,

Joe (https://twitter.com/JoeMilian1)

**Comment by JoeMilian** [comment]
Thank you for fixing it.

**Comment by cgiovando** [comment]
Thank you @JoeMilian for reporting it!
