### ISSUE TITLE
Authorization Error on Login process.

### ISSUE THREAD

**Issue by mapconcierge** [hotosm/openaerialmap#150]
When I login into the OpenAerialMap using Google and Facebook accounts, then Authorization Error will appear on the Login process.

<img width="537" alt="スクリーンショット 2021-10-18 10 17 08" src="https://user-images.githubusercontent.com/416977/137653246-1094fc4e-0f68-4451-8701-9286caa40f29.png">

We can't upload our data now...

<img width="561" alt="スクリーンショット 2021-10-18 10 02 36" src="https://user-images.githubusercontent.com/416977/137653254-bc094a3c-29e8-43c6-bef2-8c94fd456042.png">

<img width="732" alt="スクリーンショット 2021-10-18 10 14 35" src="https://user-images.githubusercontent.com/416977/137653251-f6bedf07-bffe-4c87-b12c-2fa40ad16995.png">

Please confirm Google's policies.
http://api.openaerialmap.org/oauth/google

---

## my machine specificationas:
 * macOS 10.15.6 Catalina
 * Chrome verstion: 94.0.4606.81

**Comment by dakotabenjamin** [comment]
We replaced the outdated Google API with a new one, login using Google works again.
