### ISSUE TITLE
Create Open Imagery Network organization

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#18]
Need to create an Open Imagery Network organization on Github. Do we want to use one of the following names? 

  - `openimagerynetwork`
  - `open-imagery-network`

I recommend just doing `openimagerynetwork`. If everyone agrees, I can spin up a github organization as a next action to close this out. 

cc @cgiovando @lossyrob @scisco @kamicut @ricardomestre

**Comment by lossyrob** [comment]
:+1: `openimagerynetwork`

**Comment by wonderchook** [comment]
openimagerynetwork!! do it! :+1:

**Comment by smit1678** [comment]
Created: https://github.com/openimagerynetwork. Invites pending. Closing this out.
