### ISSUE TITLE
Meta Data

### ISSUE THREAD

**Issue by colek42** [hotosm/OpenAerialMap#19]
Remote sensing data such as Band, wavelength extent, camera location, camera rotation, etc to the meta data

**Comment by cgiovando** [comment]
Hi @colek42 - thanks for the note, but unfortunately this it out of OAM's scope for the moment, as it will only deal with RGB/RGBA "true color" optical imagery. The [Open Imagery Network](https://github.com/openimagerynetwork) may at some point host more comprehensive EO data types, but for now it's also only focused on simple "RGB imagery".
