### ISSUE TITLE
Travis account

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#21]
We use [Travis CI](https://travis-ci.org/) to help manage testing, building, and deploying. It's free for open source projects. We'd recommend using it in both the oam-catalog and oam-browser applications. 

@cgiovando Does HOT have an existing Travis account? If not, we can set one up.

**Comment by althio** [comment]
https://travis-ci.org/hotosm/ exists already for hotosm/osm-tasking-manager2

**Comment by smit1678** [comment]
@althio excellent, thanks.
