### ISSUE TITLE
Imagery Browser: Tech approach 

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#25]
Based on our [strategy approach](https://github.com/hotosm/OpenAerialMap/wiki/Catalog-API---Browser:-Initial-Strategy-and-Approach), we've been looking into using [React](https://facebook.github.io/react/) as a javascript framework for the front-end browser and have done some initial testing. Based on the storyboard, there will be some key needs for any framework that is chosen:  

1. A lot of rendering on the front-end
  - API sends a lot of footprint data and metadata
  - Viewer needs to selectively render quickly according to user interaction
2. Views need to interact with and depend on each other
  - Map view and side bar communicating click, hover, and other events
3. Experience with leaflet ecosystem
  - A framework that interacts well with leaflet and mapbox.js

For these reasons we're going to start building with React. We've built a few prototypes involving a map view and React views with satisfactory results. We'll update with any additional information.

**Comment by lossyrob** [comment]
I've had minimal but good experiences with React, +1

**Comment by tmcw** [comment]
> Experience with leaflet ecosystem

This is pretty well-covered by the [react with third-party libraries page](http://facebook.github.io/react/tips/use-react-with-other-libraries.html) - you can use lifecycle methods to prop up, dispose, and update Leaflet maps at the right moments.

> Views need to interact with and depend on each other

Conceptually yes, but this is somewhat mixed - a lot of times it's not events that are passed but state changes, wether as routes or system-wide state propagated by a store. Detail views can communicate with react-router - a link on the sidebar results in a navigation change, and this re-centers and updates the map as necessary and vice versa.
