### ISSUE TITLE
Typhoon Ruby UAV imagery, Philippines

### ISSUE THREAD

**Issue by maning** [hotosm/OpenAerialMap#32]
(just a stub ticket for now, will add details later)
please add new data tag

**Comment by olafveerman** [comment]
Hey @maning 
We're about the upload the imagery you passed us, which is great btw. For appropriate attribution, could you provide us with:

1. provider (name of person / org)
2. date it was captured
3. contact (name + email)

for each of these scenes?

### tyhpoon-ruby
- arteche_mosaic_group1.tif
- canvis_mosaic_group1.tif
- dolores_2_mosaic_group1.tif
- dolores_f1_mosaic_group1.tif
- oras_f1.tif
- oras_f2.tif
- san_policarpio_mosaic_group1.tif

### typhoon-yolanda
- tacloban_part_1.tif
- tacloban_part_2.tif
- tacloban_part_3.tif
- tacloban_part_4.tif
- tacloban_part_5.tif
- tacloban_part_6.tif
- tacloban_part_7.tif
- UP_Tacloban_2.tif
- UP_Tacloban.tif

**Comment by maning** [comment]
Details below:

* Typhoon Yolanda
 * provider (name of person / org) - Jeremy Heesu Sohn  COREPHIL Data Services
 * date it was captured - November 15, 2103
 * contact (name + email) - Jeremy Heesu Sohn - jeremyheesu@gmail.com 
 * license - CC-BY

* Typhoon Ruby
 * provider (name of person / org) - SkyEye Inc.
 * date it was captured - December 2014
 * contact (name + email) - Edgar Ilaga - edgarilaga@skyeyeproject.com 
  * license - CC-BY

**Comment by olafveerman** [comment]
Thanks for this @maning We'll post back when the imagery is uploaded

cc @smit1678 @nbumbarger

**Comment by olafveerman** [comment]
@maning We've uploaded the imagery to the S3 buckets. We're ironing out a minor issue with a thumbnail, but otherwise it's looking great. Thanks again!

**Comment by maning** [comment]
Great!  btw, I forgot to include that the Typhoon Ruby has a tms from OSM-FR server, can you add it in the metedata: `http://imagery.openstreetmap.fr/tms/1.0.0/rubyph/{zoom}/{x}/{y}.png `

**Comment by maning** [comment]
tacloban_part_1.tif metadata is wrong.  It should be the same as the rest of the corephil data.

**Comment by olafveerman** [comment]
We've updated the meta files to include the TMS and corrected part_1. Thanks
