### ISSUE TITLE
Imagery for Ulaanbaatar, Mongolia

### ISSUE THREAD

**Issue by mapmeld** [hotosm/OpenAerialMap#34]
Hi!

We recently did [an OpenStreetMap event](http://www.ulaanbaatar.mn/content/show/13136) in Mongolia where students traced features from 100 sq km of UAV/drone imagery.

You can see one part of the imagery at https://api.tiles.mapbox.com/v4/the-asia-foundation.yoc41y1o/page.html?access_token=pk.eyJ1IjoidGhlLWFzaWEtZm91bmRhdGlvbiIsImEiOiJpODl0Xy00In0.on3pFdtDeQSAC04tryO_hA#20/47.94664/106.94043

I haven't heard yet whether the city will continue hosting the imagery on MapBox and give permission to openly license it. But if they approve this, I'm wondering if OpenAerialMap is the right place to go.

**Comment by jflasher** [comment]
Hi @mapmeld, this is great imagery and I think it'd definitely have a place in OAM. Do you have access or the ability to share the original image files? Having both the image files as well as the tiled maps is most helpful. 

Any idea on the timeline for when the city will make a decision?

**Comment by mapmeld** [comment]
@jflasher we have original images, a big TIF mosaic which combines and georectifies all the imagery (I believe that's the right word), and the MBTiles which we uploaded to MapBox

I can make a recommendation to the Asia Foundation and we'll ask the city to approve this for free use. HOT-OSM / OAM would then be able to host the imagery?

**Comment by jflasher** [comment]
That sounds great @mapmeld, we can get this imagery hosted and available for OAM if it can be openly licensed. Note that to be included, it will need to follow [OIN guidelines](https://github.com/openimagerynetwork/oin-register) and be licensed [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/).

**Comment by mapmeld** [comment]
@jflasher we're revisiting this issue, as storing the full-resolution tiles is proving to be expensive!

What's the best way to get the imagery to you (delivering a hard drive?)

**Comment by smit1678** [comment]
@mapmeld Awesome. I think we have a couple options: 

  - One method is the new OAM uploader: http://upload.openaerialmap.org/. If you have these stored at some publicly accessible URL, you can submit to OAM through the Uploader. We can get you a token to submit. 

  - If you don't have them stored somewhere, I just sent you a Dropbox file request invite if that is a useful. You should be able to upload the files to the folder and this will only hit our quota.

  - Last option is that @jflasher will be in UB next week. You guys could do a hard drive swap.
