### ISSUE TITLE
DigitalGlobe imagery for Dar es Salaam

### ISSUE THREAD

**Issue by PaulUithol** [hotosm/OpenAerialMap#41]
As discussed with @cgiovando and @smit1678.

1. Provider: DigitalGlobe (through American Red Cross)
2. Date: think I can derive 6 December 2014 from the file names (like 14DEC06074441-S3DS_R23C3-054428929030_01_P001.TIF)
3. License: "License is open and can be used for OpenStreetMap"; working out what it'd be exactly.

As the whole imagery is rather large, and there were issues uploading before, I'm looking specifically for "tileName: R36C2, fileName: 14DEC06074441-S3DS_R36C2-054428929030_01_P001.TIF" and "tileName: R36C3, fileName: 14DEC06074441-S3DS_R36C3-054428929030_01_P001.TIF" for now (directly North of the previous area, Keko).

We could also use "tileName: R37C1, fileName: 14DEC06074441-S3DS_R37C1-054428929030_01_P001.TIF" and "tileName: R38C1, fileName: 14DEC06074441-S3DS_R38C1-054428929030_01_P001.TIF", as this covers another two of our focus wards.

**Comment by smit1678** [comment]
@PaulUithol Awesome. We'll need to tag it with a CC-BY 4.0 license according to [OIN requirements](https://github.com/openimagerynetwork/oin-register).
