### ISSUE TITLE
Tutorial for not developter?

### ISSUE THREAD

**Issue by Basti77** [hotosm/OpenAerialMap#44]
Is there somewhere a tutorial on how to upload photos?

Here is a lot written about the software, but not how to use them.
I'm a pilot and not a developer and would like to share my results, but do not know how it works.
My pictures were all created with the trial Version of Pix4D Mapper.

**Comment by cgiovando** [comment]
Hi @Basti77 - sorry for the slow reply - we finally have some docs drafted with instructions:

http://docs.openaerialmap.org/uploader/getting-started/

Feel free to reach out if you have any question and would like to request an upload token.
