### ISSUE TITLE
Allow upload via TMS only service

### ISSUE THREAD

**Issue by maning** [hotosm/OpenAerialMap#45]
We have a case where the original tif files cannot be recovered anymore, but a TMS exist.  Using the upload API, we cannot complete the form since it requires a URL to fetch the original GTiffs.  Please allow to sharing only TMS endpoints.

**Comment by cgiovando** [comment]
Hi @maning - just a quick update on this, as it's been discussed as part of new PacDID related development. I'm going to tag it here and add some relevant discussions:

https://github.com/hotosm/oam-browser/issues/85
https://github.com/hotosm/oam-server/issues/6
