### ISSUE TITLE
Upload Form Validation Issue

### ISSUE THREAD

**Issue by pierotofy** [hotosm/OpenAerialMap#47]
It seems that the Sensor field "Type/Model (optional)" is not really optional. Leaving it blank causes the form validation logic to fail.

https://upload.openaerialmap.org/#/

**Comment by smit1678** [comment]
Thanks for flagging @pierotofy. This was fixed in https://github.com/hotosm/oam-uploader/commit/f509390df03ce7ccc9ae10edd3c506a1e867a829
