### ISSUE TITLE
Providing OAM data via WMS services

### ISSUE THREAD

**Issue by matthewhanson** [hotosm/OpenAerialMap#48]
Currently, the data in OAM is browsable, but often only the thumbnail is viewable unless there is a TMS that has been separately supplied by the data provider.  In this case users can use the OAM interface to view the full resolution datasets using the TMS, however there is currently not a good way to view this data in a desktop GIS program such as QGIS (there is a plugin, but currently does not work very well, if at all). Providing WMS/WMTS services to view the OAM data would allow more flexibility in how users are able to interact and view the data.

There are three potential approaches here, the first one being the traditional method and the others being experimental approaches that may not be fast enough to work in practice.
1. Run a WMS server with locally backed storage
   The traditional approach here would be to use any one of several WMS servers such as GeoServer or MapServer. WMTS is a service essentially the same as WMS, but one that can utilize cached tiles, and at least in the case of GeoServer this is mostly transparent to the user.  The integrated web tile cache will cache rendered tiles as they are requested, so subsequent requests will utilize the cached tiles (as long as the client supports WMTS).  There are many options for caching tiles and for WMS servers, including Mapnik, TileStache, TileCache.   Some offer the ability to store the actual tile caches on an S3 backed store. Because tiles themselves are small, and multiple tiles can be fetched simultaneously, this can be a viable storage method to keep costs for storage of a large number of tiles. 
   However, source data can potentially be much larger, and encompass an area far larger than what is required.  To provide this data via WMS, it needs to be stored locally, so the renderer can read it as needed in order to create the tiles, which are then cached.  There are some potential strategies here to sync the data from S3 so that local machines may not actually require persistent storage, but could be configured in a cluster where s3 data is synced, but tiles are stored on S3 which can be accessed by any operating WMS server.   The main underlying problem persists though, all of the data on OAM needs to be stored on some sort of local storage, which would be a much larger cost than S3.
2. Run a WMS server with S3 backed storage
   The S3 storage could be mounted on a server and treated as a local store.  While a few years ago the tools were not available to provide this in a stable enough manner, the s3fs has come a long way since then. With an aggressive pre-tiling strategy, this would provide an equally effective way to view the data, presuming tiles have already been rendered. The question here is if generating the tiles off of an S3 data store is at all practical (which may be different depending on the specific combination of rendered and tile caching program used), as well as if it's at all operational when the tiles don't exist and must be generated on the fly.   This approach uses all existing components, but would require testing to see if it is even a viable approach.
3. Run custom WMS using GDAL based smart S3 reader.
   GDAL2 contains an S3 driver that allows piecewise reading of data files on S3 (although not all file formats are supported).  Theoretically it would be possible to have a WMS server use a custom reader to efficiently read the portion of the scene to be rendered at a specific zoom level (by using overviews contained in the file).   Such an approach would need additional research and a more detailed design to determine how a WMS renderer might be modified to support such a custom data reader.

**Comment by mojodna** [comment]
I'm working on a variant of (3) that exposes a TMS against S3-hosted source data (+ overviews) using Lambda, basically what @lossyrob and I were originally hoping to do with the OAM tiler (and to facilitate a worldwide mosaic). If there's a way to run a WMS backed by tiles, these approaches may dovetail.

Or would a TMS suffice?

(The problem is fundamentally the same: windowing + resampling source imagery using sane resources.)

Rob and I tried using s3fs (and yas3fs) last year and were ultimately pretty disappointed. Of all the options, EFS seemed the most promising, but the costs were higher than we wanted and it duplicated data that was already being stored on S3.

**Comment by matthewhanson** [comment]
Thanks for this @mojodna , this is great.   I was suspecting that s3fs wouldn't offer the performance necessary here.    I'm not entirely sure what the user community would prefer here, maybe a TMS would be sufficient. TMS is already provided for some of the data (most notably the L8 data), but requires the provider to supply that on their own.    Is this something you are actively working on, and is it open?

**Comment by mojodna** [comment]
It is, but not specifically for OAM. This is the ~4th iteration intended for offline tile generation w/ POSM, but adaptable for Lambda (2 prior iterations are generating hillshades for maps.stamen.com/terrain and client imagery, both on Lambda and reading from S3):

https://github.com/mojodna/posm-imagery-api/blob/master/app.py

(Relevant functions are `render_tile`, `read_tile`, `get_tile`. Pre-processing occurs in `place_file`, `create_metadata`, `create_overviews`, and `create_warped_vrt`.)

If that link 404s (it's a temporary location), look in https://github.com/AmericanRedCross/posm-imagery-api instead.

I haven't tackled mosaicking / compositing yet, so no unified TMS so far.

**Comment by smit1678** [comment]
WMTS implemented https://github.com/hotosm/OpenAerialMap/issues/60
