### ISSUE TITLE
Edit in josm 

### ISSUE THREAD

**Issue by humano** [hotosm/OpenAerialMap#49]
I uploaded a picture, but the links do not appear to tms and / or edit it with josm, should I wait to work with her? Or someone must manually update the database?

https://beta.openaerialmap.org/#/-75.34423828125,4.456292856579885,11/0322321023121/57f036c2b0eae7f3b143a87c?_k=6592kt

https://mega.nz/#!PpFTTAaA!0EmzDCI5z92D0zBhJZku7hpQ8_VqIwzo3WAd3bsL3Ms

**Comment by smit1678** [comment]
@humano a TMS is not automatically generated yet. In order for the open in JOSM button to appear, it needs to have one generated or provided when uploaded. I will get one generated and post here when it's ready. 



		_____________________________

**Comment by smit1678** [comment]
@humano - TMS is available for this image, scroll down on the side bar: https://beta.openaerialmap.org/#/-75.34997284412384,4.453458304676604,17/03223210231212101/57f036c2b0eae7f3b143a87c?_k=og6s9h. You should be now able to open this image in JOSM.
