### ISSUE TITLE
Documentation for setting up, configuring and managing a local OAM instance

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#51]
From [OAM core work](https://github.com/hotosm/OpenAerialMap/wiki/OAM-development-related-to-PacDID-project#oam-core), need to write and add configuration options for how to deploy a complete local OAM instance. 

Need to write up what our goal is here and the key pieces that will define an entire local OAM instance first before we do any work.

**Comment by smit1678** [comment]
@kamicut Below is some of the feedback I've collected as well as a review from me. Anything else you think we should add? 

### All components 
- [ ] using docker-compose is going to be critical for helping piece together and deploy all components. Tracking this in https://github.com/hotosm/OpenAerialMap/issues/52.

### OAM Catalog
- @mojodna's changes will impact some of this and we'll need to work to integrate. 
- [ ] newrelic.js config not documented
- [ ] recommendations for how to run the worker periodically when not using Heroku
- [ ] documentation deployment and generation 

### Uploader API
- General feedback: having more detailed documentation around environment variables, initializing with default variables to get developing quicker
- [ ] newrelic.js config not documented
- [ ] describe admin setup 
- [ ] describe production, local, and staging setups 
- [ ] documentation deployment and generation 

### Uploader form
- [ ] Describe config.js files setup for different environments

### OAM Admin
- [ ] Describe config.js files setup for different environments

### Browser
- [ ] Describe config.js files setup for different environments
- [ ] describe map layers configuration more

### OAM Status
- [ ] how it fits in
- [ ] match format to other docs
- [ ] need to describe endpoints more
- [ ] configuration 

### OAM Docs
- [ ] running locally, baseurl config, etc

### Openaerialmap.org
- [ ] Describe config.js files setup for different environments

**Comment by danielfdsilva** [comment]
@smit1678 in relation to "describe production, local, and staging setups" of the uploader api. There are no separate config files for different setups. Since everything is set by env variables is just a matter of exporting the correct values

**Comment by kamicut** [comment]
We've moved to a software cron for the docker based `oam-catalog` and documented the docker based setup. Some of the documentation might change for the uploader based on https://github.com/hotosm/oam-uploader-api/pull/66
