### ISSUE TITLE
Develop Docker or scripts to support configuration and deployment (of all components)

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#52]
From [OAM Core work](https://github.com/hotosm/OpenAerialMap/wiki/OAM-development-related-to-PacDID-project#oam-core), need to develop Docker or scripts to support configuration and deployment (of all components). Related to #51, and need to define all the components of a local OAM before we build this out.

**Comment by smit1678** [comment]
Based on how we're moving forward for OAM production (moving some components from Heroku to AWS), plus in an effort to ease development and non-HOT production setup, an approach using `docker-compose` could be a good way to orchestrate all the components together. 

@davidneudorfer Other details regarding Docker that we need to consider and work on that will be helpful for you?

**Comment by davidneudorfer** [comment]
Thanks @smit1678. All good on my end. Looking forward to discussing the proposed infrastructure and pipeline once there's a plan.

**Comment by olafveerman** [comment]
Based on our conversation this morning, here are some notes and next steps.

## Approach
Moving forward, we will fully containerize the Uploader API, the Catalog API, and OAM Status and use Docker compose files for deployment. This moves the databases from hosted instances to containers on the same machine and allows the full ecosystem to on a single cloud provider like AWS.

The static frontend components don't need to be containerized and can be served using a static file server, such as nginx, GH Pages, or some CDN.

## Next steps

- OAM Catalog API - https://github.com/hotosm/oam-catalog/issues/84
  - [ ] build a Docker compose file
  - [ ] containerize the API
  - [ ] containerize the scheduled worker and write some code to substitute the Heroku scheduler
  - [ ] use the [Mongo Docker container](https://hub.docker.com/_/mongo/)
  - [ ] document the Readme
- OAM Uploader API
  - [ ] review PR  - https://github.com/hotosm/oam-uploader-api/pull/66
  - [ ] document the Readme
- OAM Status - https://github.com/hotosm/oam-status/issues/9  
  - [ ] build a Docker compose file
  - [ ] containerize the code
  - [ ] document the Readme
- [ ] Update documentation in the 'Roll your own' section of OAM docs

cc @davidneudorfer @smit1678 @mojodna @cgiovando

**Comment by kamicut** [comment]
With the final work on the oam-catalog https://github.com/hotosm/oam-catalog/issues/84 I think this is done.
