### ISSUE TITLE
Corrupt source

### ISSUE THREAD

**Issue by mojodna** [hotosm/OpenAerialMap#58]
Discovered when attempting to transcode: http://hotosm-oam.s3.amazonaws.com/0transparent_javier_july2015_mosaic_group1.tif

QGIS loads it fine (possibly because it's not reading everything), but `gdal_translate` fails when attempting to transcode it:

```
ERROR 1: TIFFFillStrip:Read error at scanline 18784; got 26082 bytes, expected 70875
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: /tmp/0transparent_javier_july2015_mosaic_group1.tif, band 1: IReadBlock failed at X offset 0, Y offset 18785
ERROR 1: GetBlockRef failed at X block offset 0, Y block offset 18785
```

For now, it's omitted from the replacement OIN bucket.

/cc @smit1678

**Comment by smit1678** [comment]
@mojodna Nice catch, interesting. Any insight on why this is failing that we can document so it can be fixed prior to uploading into OAM?

**Comment by mojodna** [comment]
Nope, sadly.
