### ISSUE TITLE
WMTS endpoints

### ISSUE THREAD

**Issue by mojodna** [hotosm/OpenAerialMap#59]
(This relates to `oam-catalog`, `oam-browser`, `oin-metadata-spec`, and possibly `oam-uploader-api`.)

Both Mapbox and the dynamic tiler support WMTS. How should we advertise this within OAM? As an unspecified metadata property (sibling of `properties.{sensor,tms}`)?

How should it be surfaced when browsing?

Should the catalog expose an über WMTS endpoint that incorporates / points to all known endpoints?

**Comment by smit1678** [comment]
> Both Mapbox and the dynamic tiler support WMTS. How should we advertise this within OAM? As an unspecified metadata property (sibling of properties.{sensor,tms})?

Yeah I think we put it as an optional element in `properties.{}`. Similar to how we're handling `license` and `tags`. Unless there is reason to look to change that up. 

> How should it be surfaced when browsing?

Perhaps we look to add it as a selection here?: 

![](https://api.monosnap.com/rpc/file/download?id=DkKGTvTzYu776PhafW5eAyHCbuaL5Z)

> Should the catalog expose an über WMTS endpoint that incorporates / points to all known endpoints?

Is this possible right now?

**Comment by mojodna** [comment]
There's no obvious "open with..."  for WMTS, so we probably want to add it as another text area w/ "Copy to clipboard" enabled.

> Yeah I think we put it as an optional element in properties.{}. Similar to how we're handling license and tags. Unless there is reason to look to change that up.

Sure. `properties.wmts`?

> Is this possible right now?

I think so, with some extra work. I can't remember if WMTS can delegate to other endpoints or if we'd need to load and duplicate all of the available ones (zoom ranges are particularly repetitive).

**Comment by smit1678** [comment]
> There's no obvious "open with..." for WMTS, so we probably want to add it as another text area w/ "Copy to clipboard" enabled.

Yes

> properties.wmts? 

Yes, I think so. Bringing that convo home in #55 

> I think so, with some extra work. I can't remember if WMTS can delegate to other endpoints or if we'd need to load and duplicate all of the available ones (zoom ranges are particularly repetitive).

Maybe something to punt on and address after the new uploader process is finished?

**Comment by mojodna** [comment]
> Maybe something to punt on and address after the new uploader process is finished?

Yup, I'm on board with that.

**Comment by smit1678** [comment]
I added the Copy to Clipboard to get WMTS url to the `oam-browser` repo issues: https://github.com/hotosm/oam-browser/issues/189.
