### ISSUE TITLE
Is map.openaerialmap.org dead?

### ISSUE THREAD

**Issue by kozuch** [hotosm/OpenAerialMap#65]
Looks like the openaerialmap.org web is not very responsive anymore... anyone knows what is going on there? Is there another place where one can upload freely licensed (possibly self made) aerial imagery?

**Comment by smit1678** [comment]
@kozuch Not dead at all actually. You can access available imagery at https://map.openaerialmap.org/ and then you can upload imagery that you collected directly at https://upload.openaerialmap.org. You can read more about the project and documentation at https://docs.openaerialmap.org/. 

If you have questions about uploading your imagery, there is a chat available at: https://gitter.im/hotosm/OpenAerialMap.
