### ISSUE TITLE
Need a disclaimer page/statement

### ISSUE THREAD

**Issue by bgirardot** [hotosm/OpenAerialMap#69]
We need a page that clearly spells out that usage of imagery from OAM means that the user totally assumes all responsibility for use of the imagery.

I can see a scenario where potential contributors are concerned about exposing themselves to liability by making their imagery available through OAM. Consumers of imagery should be made aware it is provided as is, with no warranty as to fitness or accuracy.

Probably needs real legal expertise to draft.

However, as providers release under a cc license, they are automatically including this disclaimer from the cc-by 4.0 license:

> Section 5 – Disclaimer of Warranties and Limitation of Liability.
> Unless otherwise separately undertaken by the Licensor, to the extent possible, the Licensor offers the Licensed Material as-is and as-available, and makes no representations or warranties of any kind concerning the Licensed Material, whether express, implied, statutory, or other. This includes, without limitation, warranties of title, merchantability, fitness for a particular purpose, non-infringement, absence of latent or other defects, accuracy, or the presence or absence of errors, whether or not known or discoverable. Where disclaimers of warranties are not allowed in full or in part, this disclaimer may not apply to You.
> To the extent possible, in no event will the Licensor be liable to You on any legal theory (including, without limitation, negligence) or otherwise for any direct, special, indirect, incidental, consequential, punitive, exemplary, or other losses, costs, expenses, or damages arising out of this Public License or use of the Licensed Material, even if the Licensor has been advised of the possibility of such losses, costs, expenses, or damages. Where a limitation of liability is not allowed in full or in part, this limitation may not apply to You.
> The disclaimer of warranties and limitation of liability provided above shall be interpreted in a manner that, to the extent possible, most closely approximates an absolute disclaimer and waiver of all liability.

I am just suggesting we create a page on OAM the reiterates this above fact.

**Comment by smit1678** [comment]
@bgirardot Coming back here; agreed and let's move on this and put this at the URL http://openaerialmap.org/legal/ to build out our Terms of Service / All things legal page. 

@tombh Can you start a branch on https://github.com/hotosm/openaerialmap.org to bootstrap a page and then we can fill in with content?

**Comment by tombh** [comment]
Here's a branch with a PR on the openaerialmap.org repo, it is a new page as a starting point: https://github.com/hotosm/openaerialmap.org/pull/23

**Comment by smit1678** [comment]
This is done and first version is live on the site.
