### ISSUE TITLE
Legal issues related with the dataset I provided

### ISSUE THREAD

**Issue by NicoVargas** [hotosm/OpenAerialMap#71]
Mexico has an specific law that forbid me to share the information I uploaded. I didn't know that until now. In order to keep legal, I need to request an special permission first with in the frame of the tow legal rules: UAV regulation (co-av-23-10-r3 - 10.2 >10.2.1 > m) and the Law of the national system of statistical and geographical information (Articles 60 and 61).

I'm requesting the permission now, but until then I need that OAM delete the UAV Imagery uploaded to your public webpage. Please excuse me about that trouble, but I didn't knew about that specific legal rules until now. Once I have the proper permission, I will upload the data again, but until then, delete this data from the public domain please.

Best regards

**Comment by smit1678** [comment]
@NicoVargas Thanks for flagging and I've just resolved this by removing the images from the system. Once you have received permission, please upload again using the token you had received previously (this will still work).
