### ISSUE TITLE
Planning deployment pipeline

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#77]
From #75, one key component is to review and plan out a deployment pipeline. Currently, we run backend components on Heroku, AWS and frontend components on Github Pages. 

Tools like https://flynn.io or https://kubernetes.io have been discussed in #75, as well as @davidneudorfer has been using https://www.terraform.io/ as well as https://aws.amazon.com/elasticbeanstalk/ in deployment of other HOT tools. 

Need to plan out and agree upon our infrastructure setup to run tests, build, and deploy both frontend and backend code.

**Comment by tombh** [comment]
Just to very briefly give my current thinking on this. Only the dynamic tiler has any exceptional hosting requirements, so I would like to see everything else deployed to a single platform, personally I'd vote for Flynn. I think it would be good for HOT as a whole to have experience of a adhering to good 12 Factor App standards (which Flynn requires).

However, currently the dynamic tiler is very tightly coupled with the backend, which means the backend has to follow the dynamic tiler's requirements. Which means I don't think it's worth adding *yet another* deployment mechanism to the mix until the dynamic tiler has been isolated into its own app.

**Comment by cgiovando** [comment]
@david-hotosm let's use the OAM deployment case to implement the general HOT infrastructure strategy. Would be critical for the Sep 18-22 sprint to have ideas laid out in advance on how OAM can be deployed effectively across resources with tools like mentioned above. We basically need to have OAM deployed according to the new strategy by the end of that week for PacDID testing with stakeholders the week after.

@tombh your comment on the dynamic tiler is two months old - wondering if with recent progress by @mojodna we're at a point where we can easily decouple that component from everything else?

@smit1678 would be very useful to have a list or diagram showing all current OAM deployed components, their operational status, current and expected hardware requirements, cost, and details about their current deployment workflows. If this exists somewhere already and I missed it, please link it here.

Thanks!

**Comment by tombh** [comment]
Seth said last week that he's already got Marblecutter (the dynamic tiler's spirtual successor) compatible with Heroku (and by extension Flynn). AFAIK Seth will have Marblecutter and a distinct COG processor ready for September 15th.

I've written up a more comprehensive argument for a strict 12 Factor approach on the private hotosm_infra repo: https://github.com/hotosm/hotosm_infra/issues/2 To give a tl;dr ... Once Marblecutter is OAM-compatible, the entire OAM platform can be deployed with just 2 `git push` commands, 1 for the frontend and 1 for the backend. But here are many, many more advantages to 12 Factor conformance than just deployment ease; testability, scaling, onboarding new devs, and more.
