### ISSUE TITLE
squashed thumbnail image

### ISSUE THREAD

**Issue by danbjoseph** [hotosm/OpenAerialMap#79]
thumbnail can be squashed sometimes, see this [example](https://map.openaerialmap.org/#/122.0745849609375,11.410033492843773,13/132303323302131/592d9b6db0eae7f3b143ffe5?_k=oingz0)
![screen shot 2017-06-18 at 4 06 37 pm](https://user-images.githubusercontent.com/4806884/27263828-23f4f92a-5440-11e7-8445-e64de0f534b4.png)

**Comment by tombh** [comment]
Thanks for this. Just checked and it's a CSS issue, so should be easy to fix.
