### ISSUE TITLE
Develop integration for DroneDeploy App Market

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#82]
A common workflow for some users has been to leverage services from DroneDeploy. Idea here is to develop a push to OAM app for the DroneDeploy App Market. 

Documentation here: https://dronedeploy.gitbooks.io/dronedeploy-apps/content/.

**Comment by tombh** [comment]
Awesome idea

**Comment by mojodna** [comment]
@sharkinsspatial has been working on this.

**Comment by sharkinsspatial** [comment]
Closed by https://github.com/hotosm/oam-dronedeploy and https://github.com/hotosm/oam-catalog/pull/124.
