### ISSUE TITLE
Request for Token

### ISSUE THREAD

**Issue by chapw** [hotosm/OpenAerialMap#92]
I am interested in contributing some ortho imagery obtained by a DJI drone to the OAM database. The regular token request tool doesnt work for me on the OAM website.

Can the token be issued here?

Chaplin Williams
Master student - Geospatial Technologies - IFGI Muenster.

**Comment by smit1678** [comment]
@chapw Apologies for no response here. The token request tool has been replaced by user accounts: https://blog.openaerialmap.org/new-in-oam-user-accounts-6ccd10449897. Have you been able to login and sign up for an account?

**Comment by chapw** [comment]
Yes thank you Nate,

all accomplished and my upload works fine.

Kind regards,

Chaplin
