### ISSUE TITLE
Would like to be able to see how many medium and high res imagery sets cover an area

### ISSUE THREAD

**Issue by bgirardot** [hotosm/OpenAerialMap#93]
At the moment my only choices are all, low, med, high.

Since the usability of med res imagery varies somewhat, I would like to be able to see how many med and high res images cover an area.

But as far as I can tell, all I can do is look at med, then switch and look at high.

**Comment by bgirardot** [comment]
This is very minor and could be closed. I think I am talking about

Low
Med
High

In the filter popdown menu being changed to show this:

Low (4)
Med (2)
High (0)

**Comment by cgiovando** [comment]
Closing in favor of https://github.com/hotosm/oam-browser/issues/179
