### ISSUE TITLE
Highly compressed option for imagery download

### ISSUE THREAD

**Issue by cgiovando** [hotosm/OpenAerialMap#98]
Would be very useful to have the option to download every image in OAM in a super compressed format (GeoTIFF with internal JPEG compression, ECW, JP2, etc).

This would help those users in limit bandwidth environments and that only need imagery for visual inspection, assessment or mapping. Lossy compression would still be fine for most applications.

**Comment by mojodna** [comment]
GeoTIFFs linked to from the catalog already fulfill this criteria (they're COGs (well, almost), crunched as much as possible).
